# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eve's Fish Bar
brand_1: Restaurant Eve
brand_1_url: http://restauranteve.com
brand_2: Society Fair
brand_2_url: http://societyfair.net
brand_3: BarPX
brand_3_url: http://barpx.com
brand_4: Eamonn's
brand_4_url: http://eamonnsdublinchipper.com
email: webmaster@eatgoodfoodgroup.com
description: > # this means to ignore newlines until "baseurl:"
  Eve's Fish Bar is a new venture by the eat good food group
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evesfishbar.com" # the base hostname & protocol for your site

# Assets
cdn_path: https://dl.dropboxusercontent.com/u/6041318/eatgoodfoodgroup.com

# Social media accounts
twitter_username_eamonns: eamonnschipper
twitter_username_eve: restaurant_eve
twitter_username_sf: societyfair
twitter_username_px: BarPX
facebook_username_eamonns: EamonnsADublinChipper
facebook_username_eve: restauranteve
facebook_username_sf: societyfair
facebook_username_px: BarPX
instagram_username_eamonns: EamonnsADublinChipper
instagram_username_eve: restaurant_eve
instagram_username_sf: societyfair
instagram_username_px: barpx

# Build settings
markdown: kramdown

# Configure prose.io.
prose:
  rooturl: '_posts'
  siteurl: 'http://eatgoodfood.github.io/evesfishbar'
  relativeLinks: 'http://eatgoodfood.github.io/evesfishbar/links.jsonp'
  media: 'media'
  ignore:
    - index.html
    - _config.yml
    - CNAME
    - /_layouts
    - /_includes
    - /_plugins
    - /_sass
  siteurl: "http://evesfishbar.com"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Choose Tags"
          options:
            - name: "Update"
              value: "update"